name: hp
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - rasterio
  - pip:
      - aim~=3.17.5
      - einops~=0.7
      - geopandas==0.14.2
      - jupyterlab==4.0.11
      - lightning==2.1.3
      - matplotlib
      - numpy==1.26.3
      - opencv-python~=4.9
      - pandas==2.2.0
      - pycocotools~=2.0
      - scikit-learn==1.4.0
      - seaborn==0.13.1
      - torch==2.1.1
      - torchvision==0.16.1
      - torchmetrics==1.3.0
      - timm~=0.9.12
platforms:
  - linux-64

