version: '3'
services:
  hpdb:
    image: developmentseed/hpdb:v1
    build:
      context: ./dockerPG
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_HOST: 'localhost'
      POSTGRES_DB: 'db_passport'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      SET_SERVER_CONFING: 'true'
      MACHINE_TYPE: 'xlarge'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  hpdev:
    image: developmentseed/hpdev:v1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - ./:/mnt/data
        - ./../../Downloads/:/host_files
        - ~/.aws:/root/.aws
