item {
  id: 1
  name: 'complete'
}
item {
  id: 2
  name: 'incomplete'
}
item {
  id: 3
  name: 'poor'
}
item {
  id: 4
  name: 'fair'
}
item {
  id: 5
  name: 'good'
}
item {
  id: 6
  name: 'mix-other-unclear'
}
item {
  id: 7
  name: 'brick_or_cement-concrete_block'
}
item {
  id: 8
  name: 'wood_polished'
}
item {
  id: 9
  name: 'stone_with_mud-ashlar_with_lime_or_cement'
}
item {
  id: 10
  name: 'corrugated_metal'
}
item {
  id: 11
  name: 'wood_crude-plank'
}
item {
  id: 12
  name: 'container-trailer'
}
item {
  id: 19
  name: 'plaster'
}
item {
  id: 20
  name: 'adobe'
}
item {
  id: 13
  name: 'secured'
}
item {
  id: 14
  name: 'unsecured'
}
item {
  id: 15
  name: 'residential'
}
item {
  id: 16
  name: 'critical_infrastructure'
}
item {
  id: 17
  name: 'mixed'
}
item {
  id: 18
  name: 'commercial'
}
